-- ══════════════════════════════════════════════════════════════════════════
-- v5.37.0 · Buchhaltung: Abrechnung freigeben → Chatter lädt Rechnung hoch →
--           ihr drückt „Bezahlt“ (Datum + Betrag werden gespeichert)
--
-- 1) Tabelle chatter_abrechnungen (eine Zeile je Chatter und Zeitraum)
-- 2) Schutz-Trigger: Chatter dürfen NUR ihre Rechnung hochladen, nichts
--    anderes ändern (Betrag, Status „bezahlt“ … bleiben bei euch)
-- 3) Privater Speicherordner „rechnungen“ (nur Staff + der Chatter selbst)
--
-- Ändert keine bestehenden Daten. Kann mehrfach ausgeführt werden.
-- ══════════════════════════════════════════════════════════════════════════

-- 1) Tabelle
create table if not exists public.chatter_abrechnungen (
  id                 bigint generated by default as identity primary key,
  chatter_name       text not null,
  monat              text not null check (monat ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),  -- Bezugsmonat (Kurs, „inaktiv ab“)
  von                date not null,
  bis                date not null check (bis >= von),
  frei               boolean not null default false,       -- freier Zeitraum statt ganzer Monat
  bezeichnung        text,                                 -- „September 2026“ / „27.09.–03.10.2026“
  umsatz_chat_usd    numeric(12, 2),
  umsatz_gesamt_usd  numeric(12, 2),
  basis_usd          numeric(12, 2),
  prozent            numeric(6, 2),
  nur_chat           boolean,
  auszahlung_usd     numeric(12, 2),
  kurs               numeric(10, 6),
  betrag_eur         numeric(12, 2),
  freigegeben_am     timestamptz not null default now(),
  freigegeben_von    text,
  status             text not null default 'offen'
                     check (status in ('offen', 'rechnung', 'klaerung', 'bezahlt')),
  rechnung_url       text,
  rechnung_name      text,
  rechnung_betrag    numeric(12, 2),
  rechnung_am        timestamptz,
  rechnung_von       text,
  klaerung_notiz     text,
  klaerung_am        timestamptz,
  bezahlt_am         date,
  bezahlt_betrag     numeric(12, 2),
  bezahlt_von        text,
  bezahlt_eingetragen_am timestamptz,
  erinnert_am        timestamptz,
  unique (chatter_name, von, bis)
);
create index if not exists chatter_abrechnungen_name_idx on public.chatter_abrechnungen (chatter_name, von desc);
create index if not exists chatter_abrechnungen_status_idx on public.chatter_abrechnungen (status);

alter table public.chatter_abrechnungen enable row level security;

drop policy if exists abr_lesen on public.chatter_abrechnungen;
drop policy if exists abr_anlegen on public.chatter_abrechnungen;
drop policy if exists abr_aendern on public.chatter_abrechnungen;
drop policy if exists abr_loeschen on public.chatter_abrechnungen;
drop policy if exists abr_aktiv on public.chatter_abrechnungen;
create policy abr_lesen on public.chatter_abrechnungen for select to authenticated
  using ((select public.is_staff()) or chatter_name = (select public.my_display_name()));
create policy abr_anlegen on public.chatter_abrechnungen for insert to authenticated
  with check ((select public.is_staff()));
create policy abr_aendern on public.chatter_abrechnungen for update to authenticated
  using ((select public.is_staff()) or chatter_name = (select public.my_display_name()))
  with check ((select public.is_staff()) or chatter_name = (select public.my_display_name()));
create policy abr_loeschen on public.chatter_abrechnungen for delete to authenticated
  using ((select public.is_staff()));
create policy abr_aktiv on public.chatter_abrechnungen as restrictive for all to authenticated
  using ((select public.is_active_user())) with check ((select public.is_active_user()));

-- 2) Schutz-Trigger (a_ → läuft vor anderen BEFORE-Triggern)
create or replace function public.chatter_abrechnungen_schuetzen()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  ich text := public.my_display_name();
  v   public.chatter_abrechnungen;
begin
  if auth.uid() is null or public.is_staff() then
    v := new;
  elsif old.chatter_name = ich and old.status <> 'bezahlt' then
    -- Chatter: nur die eigene Rechnung (Datei, Name, Betrag)
    v := old;
    v.rechnung_url := new.rechnung_url;
    v.rechnung_name := new.rechnung_name;
    v.rechnung_betrag := new.rechnung_betrag;
  else
    raise exception 'Keine Berechtigung für diese Abrechnung';
  end if;

  v.id := old.id;
  v.freigegeben_am := old.freigegeben_am;

  -- neue Rechnungsdatei → Zeitpunkt, wer, Status „Rechnung da“
  if v.rechnung_url is distinct from old.rechnung_url and v.rechnung_url is not null then
    v.rechnung_am := now();
    v.rechnung_von := ich;
    if v.status in ('offen', 'klaerung') then v.status := 'rechnung'; end if;
  end if;

  -- bezahlt / zurück
  if v.status = 'bezahlt' and old.status <> 'bezahlt' then
    v.bezahlt_am := coalesce(v.bezahlt_am, (now() at time zone 'Europe/Berlin')::date);
    v.bezahlt_von := ich;
    v.bezahlt_eingetragen_am := now();
  elsif v.status <> 'bezahlt' and old.status = 'bezahlt' then
    v.bezahlt_am := null; v.bezahlt_betrag := null; v.bezahlt_von := null; v.bezahlt_eingetragen_am := null;
  end if;

  if v.status = 'klaerung' and (old.status <> 'klaerung' or v.klaerung_notiz is distinct from old.klaerung_notiz) then
    v.klaerung_am := now();
  end if;
  return v;
end $$;
drop trigger if exists a_chatter_abrechnungen_schuetzen on public.chatter_abrechnungen;
create trigger a_chatter_abrechnungen_schuetzen before update on public.chatter_abrechnungen
  for each row execute function public.chatter_abrechnungen_schuetzen();

-- 3) Speicher „rechnungen“ (privat, Ordner = Name des Chatters)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('rechnungen', 'rechnungen', false, 15728640,
        array['application/pdf', 'image/jpeg', 'image/png', 'image/heic', 'image/heif', 'image/webp'])
on conflict (id) do update set public = false;

drop policy if exists rechnungen_lesen on storage.objects;
drop policy if exists rechnungen_hochladen on storage.objects;
drop policy if exists rechnungen_loeschen on storage.objects;
create policy rechnungen_lesen on storage.objects for select to authenticated
  using (bucket_id = 'rechnungen' and public.is_active_user()
         and (public.is_staff() or (storage.foldername(name))[1] = public.my_display_name()));
create policy rechnungen_hochladen on storage.objects for insert to authenticated
  with check (bucket_id = 'rechnungen' and public.is_active_user()
              and (public.is_staff() or (storage.foldername(name))[1] = public.my_display_name()));
create policy rechnungen_loeschen on storage.objects for delete to authenticated
  using (bucket_id = 'rechnungen' and public.is_staff());

-- Kontrolle: 1 · true · 3
select
  (select count(*) from information_schema.tables where table_schema = 'public' and table_name = 'chatter_abrechnungen') as tabelle,
  (select not public from storage.buckets where id = 'rechnungen') as bucket_privat,
  (select count(*) from pg_policies where schemaname = 'storage' and policyname like 'rechnungen_%') as speicher_regeln;
